#include <vector>
#include <map>
#include <set>
#include <queue>
#include <deque>
#include <stack>
#include <algorithm>
#include <utility>
#include <sstream>
#include <iostream>
#include <iomanip>
#include <cstdio>
#include <cstring>
#include <cmath>
#include <cstdlib>
#include <ctime>
#include <cassert>
using namespace std;

#ifdef DEBUG
	#define debug(...) printf(__VA_ARGS__)
	#define GetTime()	printf("Running time: %.3lf second\n",((double)clock())/CLOCKS_PER_SEC)
#else
	#define debug(...) 
	#define GetTime() 
#endif

//type definitions
typedef long long ll;
typedef double db;
typedef pair<int,int> pii;

//abbreviations
#define A first
#define B second
#define MP make_pair
#define PB push_back
#define LLD "%I64d"

//macros
#define REP(i,n) for (int i = 0; i < (n); ++i)
#define REPD(i,n) for (int i = (n)-1; 0 <= i; --i)
#define FOR(i,a,b) for (int i = (a); i <= (b); ++i)
#define FORD(i,a,b) for (int i = (a); (b) <= i; --i)
#define FORIT(it,c) for (__typeof ((c).begin()) it = (c).begin(); it != (c).end(); it++)
#define ALL(a) (a).begin(),(a).end()
#define SZ(a) ((int)(a).size())
#define RESET(a,x) memset(a,x,sizeof(a))
#define EXIST(a,s) ((s).find(a) != (s).end())
#define MX(a,b) a = max((a),(b));
#define MN(a,b) a = min((a),(b));

/* -------------- end of azaky's template -------------- */

class GameInDarknessDiv1 {
public:
	string check(vector <string> field) {
		
	}
};
 
 
// BEGIN KAWIGIEDIT TESTING
// Generated by KawigiEdit 2.1.4 (beta) modified by pivanof
bool KawigiEdit_RunTest(int testNum, vector <string> p0, bool hasAnswer, string p1) {
	cout << "Test " << testNum << ": [" << "{";
	for (int i = 0; int(p0.size()) > i; ++i) {
		if (i > 0) {
			cout << ",";
		}
		cout << "\"" << p0[i] << "\"";
	}
	cout << "}";
	cout << "]" << endl;
	GameInDarknessDiv1 *obj;
	string answer;
	obj = new GameInDarknessDiv1();
	clock_t startTime = clock();
	answer = obj->check(p0);
	clock_t endTime = clock();
	delete obj;
	bool res;
	res = true;
	cout << "Time: " << double(endTime - startTime) / CLOCKS_PER_SEC << " seconds" << endl;
	if (hasAnswer) {
		cout << "Desired answer:" << endl;
		cout << "\t" << "\"" << p1 << "\"" << endl;
	}
	cout << "Your answer:" << endl;
	cout << "\t" << "\"" << answer << "\"" << endl;
	if (hasAnswer) {
		res = answer == p1;
	}
	if (!res) {
		cout << "DOESN'T MATCH!!!!" << endl;
	} else if (double(endTime - startTime) / CLOCKS_PER_SEC >= 2) {
		cout << "FAIL the timeout" << endl;
		res = false;
	} else if (hasAnswer) {
		cout << "Match :-)" << endl;
	} else {
		cout << "OK, but is it right?" << endl;
	}
	cout << "" << endl;
	return res;
}
int main() {
	bool all_right;
	all_right = true;
	
	vector <string> p0;
	string p1;
	
	{
	// ----- test 0 -----
	string t0[] = {"A.B..","##.##","##.##"};
			p0.assign(t0, t0 + sizeof(t0) / sizeof(t0[0]));
	p1 = "Alice wins";
	all_right = KawigiEdit_RunTest(0, p0, true, p1) && all_right;
	// ------------------
	}
	
	{
	// ----- test 1 -----
	string t0[] = {"A.B..",".#.#.","#..##"};
			p0.assign(t0, t0 + sizeof(t0) / sizeof(t0[0]));
	p1 = "Bob wins";
	all_right = KawigiEdit_RunTest(1, p0, true, p1) && all_right;
	// ------------------
	}
	
	{
	// ----- test 2 -----
	string t0[] = {"#...#",".#A#.","..B..",".#.#.","#...#"};
			p0.assign(t0, t0 + sizeof(t0) / sizeof(t0[0]));
	p1 = "Alice wins";
	all_right = KawigiEdit_RunTest(2, p0, true, p1) && all_right;
	// ------------------
	}
	
	{
	// ----- test 3 -----
	string t0[] = {"##..#","A.#..","#B..#","#.##.","....."};
			p0.assign(t0, t0 + sizeof(t0) / sizeof(t0[0]));
	p1 = "Alice wins";
	all_right = KawigiEdit_RunTest(3, p0, true, p1) && all_right;
	// ------------------
	}
	
	{
	// ----- test 4 -----
	string t0[] = {"##################################################","###..................#................#........###","###.################.########.#######.########.###","###.################.########.#######.########.###","###.################.########.#######.########.###","###.################.########.#######.########.###","###.################.########.#######.########.###","###.################.########.#######.########.###","###.################.########.#######.########.###","###.################.########.#######.########.###","###..........#######........#.#######........#.###","############.#######.########.#######.########.###","############.#######.########.#######.########.###","############.#######.########.#######.########.###","############.#######.########.#######.########.###","############.#######.########.#######.########.###","############.#######.########.#######.########.###","############.#######.########.#######.########.###","############.#######.########.#######.########"
			".###","###B.........#######..........#######..A.......###","##################################################"};
			p0.assign(t0, t0 + sizeof(t0) / sizeof(t0[0]));
	p1 = "Bob wins";
	all_right = KawigiEdit_RunTest(4, p0, true, p1) && all_right;
	// ------------------
	}
	
	{
	// ----- test 5 -----
	string t0[] = {"###.#","###..","A..B#","###..","###.#"};
			p0.assign(t0, t0 + sizeof(t0) / sizeof(t0[0]));
	p1 = "Alice wins";
	all_right = KawigiEdit_RunTest(5, p0, true, p1) && all_right;
	// ------------------
	}
	
	{
	// ----- test 6 -----
	string t0[] = {".....#.##.##.#.#",".###.#.##.##....","#......B#...#.#.","#.#A#.#.#.#..##.","...#..#....#...."};
			p0.assign(t0, t0 + sizeof(t0) / sizeof(t0[0]));
	p1 = "Alice wins";
	all_right = KawigiEdit_RunTest(6, p0, true, p1) && all_right;
	// ------------------
	}
	
	{
	// ----- test 7 -----
	string t0[] = {"...#.....###....#.....#...#.#.",".#..#.##..#..#.#..###...#.....","..#..#..#...#.#..#....##.#.###",".#.#...###.#..#.#..###....#...","...##.###..#.#..#.#...#.##..#.",".#..#..#..#...#.#.#.#.#..#.#..","..#..#.#.#..#..##.#.#..#.##..#",".#.###.#.##..#.....A##......#.","#.........#.#..#.###..###.#...","..###.#.#.#..#.#....#.....#.#.",".#..#.#.####.#..#.#..#.#.###..","..#...#...#..#.#...#.#..#.#..#","#..#.#..#.#.#..###.#.#.#....#.","..#..##.##...#....#..#.#.####.","#..#...#...#..#.#..###.#......","#.#.##...#..#..#.#....#..#.#.#","....#..##.#..#....#.#.#.#...#.",".#.#..#....#.#.##..#..##..#.#.","..##.#..##.#..#..#..#...#.#...","#.#..##..#..#..#..#..##.#.#.#.","..#.#.#.#.#..#...##.#...#..#..",".##.....#..#.#.#.#..#.##.#..#.","...#.#.#..#..#.###.#..#...#.#.",".#..#....#..#.#...###.#.#..#..",".#.#.#####.#....#..#..#.##.#.#",".#...#......#.#..###B#....#...","..###..####.#..#.#...#.#.#..#.","#.#..#.#..#.#.#..#.#..#....#..","..#.##..#.#.#.####..#.#####..#","#.....#...#.#......#.......#.."};
			p0.assign(t0, t0 + sizeof(t0) / sizeof(t0[0]));
	p1 = "Bob wins";
	all_right = KawigiEdit_RunTest(7, p0, true, p1) && all_right;
	// ------------------
	}
	
	if (all_right) {
		cout << "You're a stud (at least on the example cases)!" << endl;
	} else {
		cout << "Some of the test cases had errors." << endl;
	}
	return 0;
}
// END KAWIGIEDIT TESTING
//Powered by KawigiEdit 2.1.4 (beta) modified by pivanof!
