/*
ID: a_zaky01
PROG: guard
LANG: C++
*/

#include <vector>
#include <map>
#include <set>
#include <queue>
#include <deque>
#include <stack>
#include <algorithm>
#include <utility>
#include <numeric>
#include <sstream>
#include <iostream>
#include <iomanip>
#include <cstdio>
#include <cstring>
#include <cmath>
#include <cstdlib>
#include <ctime>
#include <cassert>
#include <limits>
using namespace std;

#ifdef DEBUG
	#define debug(...) printf(__VA_ARGS__)
	#define GetTime() fprintf(stderr,"Running time: %.3lf second\n",((double)clock())/CLOCKS_PER_SEC)
#else
	#define debug(...) 
	#define GetTime() 
#endif

//type definitions
typedef long long ll;
typedef double db;
typedef pair<int,int> pii;
typedef vector<int> vint;

//abbreviations
#define A first
#define B second
#define MP make_pair
#define PB push_back

//macros
#define REP(i,n) for (int i = 0; i < (n); ++i)
#define REPD(i,n) for (int i = (n)-1; 0 <= i; --i)
#define FOR(i,a,b) for (int i = (a); i <= (b); ++i)
#define FORD(i,a,b) for (int i = (a); (b) <= i; --i)
#define FORIT(it,c) for (__typeof ((c).begin()) it = (c).begin(); it != (c).end(); it++)
#define ALL(a) (a).begin(),(a).end()
#define SZ(a) ((int)(a).size())
#define RESET(a,x) memset(a,x,sizeof(a))
#define EXIST(a,s) ((s).find(a) != (s).end())
#define MX(a,b) a = max((a),(b));
#define MN(a,b) a = min((a),(b));

inline void OPEN(const string &s) {
	freopen((s + ".in").c_str(), "r", stdin);
	freopen((s + ".out").c_str(), "w", stdout);
}

/* -------------- end of azaky's template -------------- */

#define MAXN 22
#define INF 1023123123
int n, H, h[MAXN], w[MAXN], s[MAXN], dp[1 << MAXN], ht[1 << MAXN];

int main(){
	OPEN("guard");
	cin >> n >> H;
	REP(i, n) cin >> h[i] >> w[i] >> s[i];

	RESET(dp, -1);
	dp[0] = INF;
	int ans = 0;
	REP(mask, 1 << n) {
		REP(i, n) {
			if (!(mask & (1 << i))) continue;

			ht[mask] = ht[mask ^ (1 << i)] + h[i]; // actually doing this once is enough
			if (ht[mask] >= H) ht[mask] = H;

			MX(dp[mask], min(dp[mask ^ (1 << i)] - w[i], s[i]));
		}
		if (ht[mask] >= H && dp[mask] >= 0 && (ans == 0 || dp[mask] > dp[ans])) {
			ans = mask;
		}
	}
	if (ans) {
		printf("%d\n", dp[ans]);
	}
	else {
		puts("Mark is too tall");
	}

	return 0;
}

/* Generated by UsacoTemp v3.0 */
