#include <vector>
#include <list>
#include <map>
#include <set>
#include <queue>
#include <deque>
#include <stack>
#include <bitset>
#include <algorithm>
#include <functional>
#include <numeric>
#include <utility>
#include <sstream>
#include <iostream>
#include <iomanip>
#include <cstdio>
#include <cmath>
#include <cstdlib>
#include <ctime>

using namespace std;


class EqualSums {
public:
	int count(vector <string> board) {
		int n = board.size();
		int a[100][100];
		for (int i=0; i < n; ++i) for (int j=0; j < n; ++j){
			if ('0' <= board[i][j] && board[i][j] <= '9') a[i][j] = board[i][j] - '0'; else a[i][j] = -1;
		}
		//check empty row/column
		for (int r=0; r < n; ++r){
			bool empty = true;
			for (int c=0; c < n; ++i) if (a[r][c] != -1) empty = false;
			if (empty) return 0;
		}
		for (int c=0; c < n; ++c){
			bool empty = true;
			for (int r=0; r < n; ++i) if (a[r][c] != -1) empty = false;
			if (empty) return 0;
		}
		for (int r1=0; r1 < n; ++r1){
			for (int r2=0; r2 < n; ++r2){
				
	}
};


// BEGIN KAWIGIEDIT TESTING
// Generated by KawigiEdit 2.1.4 (beta) modified by pivanof
bool KawigiEdit_RunTest(int testNum, vector <string> p0, bool hasAnswer, int p1) {
	cout << "Test " << testNum << ": [" << "{";
	for (int i = 0; int(p0.size()) > i; ++i) {
		if (i > 0) {
			cout << ",";
		}
		cout << "\"" << p0[i] << "\"";
	}
	cout << "}";
	cout << "]" << endl;
	EqualSums *obj;
	int answer;
	obj = new EqualSums();
	clock_t startTime = clock();
	answer = obj->count(p0);
	clock_t endTime = clock();
	delete obj;
	bool res;
	res = true;
	cout << "Time: " << double(endTime - startTime) / CLOCKS_PER_SEC << " seconds" << endl;
	if (hasAnswer) {
		cout << "Desired answer:" << endl;
		cout << "\t" << p1 << endl;
	}
	cout << "Your answer:" << endl;
	cout << "\t" << answer << endl;
	if (hasAnswer) {
		res = answer == p1;
	}
	if (!res) {
		cout << "DOESN'T MATCH!!!!" << endl;
	} else if (double(endTime - startTime) / CLOCKS_PER_SEC >= 2) {
		cout << "FAIL the timeout" << endl;
		res = false;
	} else if (hasAnswer) {
		cout << "Match :-)" << endl;
	} else {
		cout << "OK, but is it right?" << endl;
	}
	cout << "" << endl;
	return res;
}
int main() {
	bool all_right;
	all_right = true;
	
	vector <string> p0;
	int p1;
	
	{
	// ----- test 0 -----
	string t0[] = {"1-","-2"};
			p0.assign(t0, t0 + sizeof(t0) / sizeof(t0[0]));
	p1 = 4;
	all_right = KawigiEdit_RunTest(0, p0, true, p1) && all_right;
	// ------------------
	}
	
	{
	// ----- test 1 -----
	string t0[] = {"123","4--","--9"};
			p0.assign(t0, t0 + sizeof(t0) / sizeof(t0[0]));
	p1 = 1;
	all_right = KawigiEdit_RunTest(1, p0, true, p1) && all_right;
	// ------------------
	}
	
	{
	// ----- test 2 -----
	string t0[] = {"9--","-9-","--9"};
			p0.assign(t0, t0 + sizeof(t0) / sizeof(t0[0]));
	p1 = 271;
	all_right = KawigiEdit_RunTest(2, p0, true, p1) && all_right;
	// ------------------
	}
	
	{
	// ----- test 3 -----
	string t0[] = {"11","12"};
			p0.assign(t0, t0 + sizeof(t0) / sizeof(t0[0]));
	p1 = 0;
	all_right = KawigiEdit_RunTest(3, p0, true, p1) && all_right;
	// ------------------
	}
	
	{
	// ----- test 4 -----
	string t0[] = {"-4--","-0-2","--1-","4---"};
			p0.assign(t0, t0 + sizeof(t0) / sizeof(t0[0]));
	p1 = 10;
	all_right = KawigiEdit_RunTest(4, p0, true, p1) && all_right;
	// ------------------
	}
	
	{
	// ----- test 5 -----
	string t0[] = {"--2","02-","-10"};
			p0.assign(t0, t0 + sizeof(t0) / sizeof(t0[0]));
	p1 = 0;
	all_right = KawigiEdit_RunTest(5, p0, true, p1) && all_right;
	// ------------------
	}
	
	{
	// ----- test 6 -----
	string t0[] = {"----------1---------------0-----7-----------------","-----4--------------------------------------------","--------5-------------5-3---5---------------6-----","-------2----------1-------------------------------","-----4--------------------------------------------","-----3--------------------------------------------","-6----------5-------------------------------------","-------------------------------7---5----------6---","--------6-------------6-4---6---------------7-----","-------------4----------------5-------------------","3------------------------------------------6------","3------------------------------------------6------","-------------4----------------5-------------------","---------------2-------------------------3--------","--2------------------------------------------2----","---8---------------1-------------------3----------","---------------3----------------------------------","----7----------------5---0-----------------------5","----------------5-------------------------3---"
			"--1-","----------1---------------0-----7-----------------","-------------5----------------6-------------------","-7----------6-------------------------------------","---8---------------1-------------------3----------","-----------------------3--------------------------","----8----------------6---1-----------------------6","------------------------------------------4-----2-","-----------5---------------5----------------------","-----------------------------6--------------------","----8----------------6---1-----------------------6","----------------5-------------------------3-----1-","-------------------------------6---4--2-------5---","-6----------5-------------------------------------","--------5-------------5-3---5---------------6-----","-------------5----------------6-------------------","-----3--------------------------------------------","---------------2-------------------------3--------","---------4---------------------------6------------","-------------------------------6---4--2-"
			"------5---","------2-------------1------------22---------------","--------5-------------5-3---5---------------6-----","-----------5--3------------5----------------------","--2------------------------------------------2----","---------5---------------------------7------------","-------------4----------------5-------------------","-----------------5------------------4---6------2--","-------------------------------6---4--2-------5---","-----------------------2--------------------------","----------------6-------------------------4-----2-","-------------------------------6---4--2-------5---","--------5-------------5-3---5---------------6-----"};
			p0.assign(t0, t0 + sizeof(t0) / sizeof(t0[0]));
	p1 = 45094393;
	all_right = KawigiEdit_RunTest(6, p0, true, p1) && all_right;
	// ------------------
	}
	
	if (all_right) {
		cout << "You're a stud (at least on the example cases)!" << endl;
	} else {
		cout << "Some of the test cases had errors." << endl;
	}
	return 0;
}
// END KAWIGIEDIT TESTING
//Powered by KawigiEdit 2.1.4 (beta) modified by pivanof!
